name: Deploy Backend to Arbutus Cloud Instance

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: m2b3/scicommons-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Set up Docker metadata (tags and labels) for web image
      - name: Extract Docker metadata for web image
        id: meta-web
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web

      # Step 4: Build and push web image to GitHub Packages
      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}

      # Step 5: Set up Docker metadata (tags and labels) for celery image
      - name: Extract Docker metadata for celery image
        id: meta-celery
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-celery

      # Step 6: Build and push celery image to GitHub Packages
      - name: Build and push celery image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta-celery.outputs.tags }}
