name: Deploy Backend to Arbutus Cloud Instance

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_WEB: m2b3/scicommons-backend-web
  IMAGE_NAME_CELERY: m2b3/scicommons-backend-celery

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Extract Docker metadata for Web service
      - name: Extract Docker metadata for Web
        id: meta_web
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB }}

      # Step 4: Build and push Docker image for Web service
      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta_web.outputs.tags }}
          build-args: |
            SERVICE=web

      # Step 5: Extract Docker metadata for Celery service
      - name: Extract Docker metadata for Celery
        id: meta_celery
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CELERY }}

      # Step 6: Build and push Docker image for Celery service
      - name: Build and push Celery image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta_celery.outputs.tags }}
          build-args: |
            SERVICE=celery

      # Step 7: Setup SSH keys and known_hosts
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Step 8: Transfer docker-compose.prod.yml to the server
      - name: Transfer docker-compose.prod.yml to SERVER
        run: |
          scp -i ~/.ssh/id_rsa docker-compose.prod.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/ubuntu/deployment/docker-compose.prod.yml
